language: node_js
node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - if [ "${FLOW-}" = true ]; then npm run flow; fi
  - if [ "${LINT-}" = true ]; then npm run lint; fi
  - if [ "${TEST-}" = true ]; then npm run test:ci; fi
after_success:
  - if [ "${TEST-}" = true ]; then npm run coveralls; fi
sudo: false
env:
  global:
    - TEST=true
matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: FLOW=true TEST=false
    - node_js: "node"
      env: LINT=true TEST=false
  allow_failures:
    - node_js: "7"
    - node_js: "5"
